import React, { useState } from 'react'

const ERROR_IMG_SRC =
  'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iODgiIGhlaWdodD0iODgiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgc3Ryb2tlPSIjMDAwIiBzdHJva2UtbGluZWpvaW49InJvdW5kIiBvcGFjaXR5PSIuMyIgZmlsbD0ibm9uZSIgc3Ryb2tlLXdpZHRoPSIzLjciPjxyZWN0IHg9IjE2IiB5PSIxNiIgd2lkdGg9IjU2IiBoZWlnaHQ9IjU2IiByeD0iNiIvPjxwYXRoIGQ9Im0xNiA1OCAxNi0xOCAzMiAzMiIvPjxjaXJjbGUgY3g9IjUzIiBjeT0iMzUiIHI9IjciLz48L3N2Zz4KCg=='

// Only assets served from /images have a .webp sibling generated by scripts/optimize-images.mjs.
function webpSource(src?: string) {
  if (import.meta.env.DEV) return undefined
  if (typeof src !== 'string' || !src.startsWith('/images/')) return undefined
  return src.replace(/\.(jpe?g|png)$/i, '.webp')
}

function mobileWebpSource(src?: string) {
  if (import.meta.env.DEV) return undefined
  if (typeof src !== 'string' || !src.startsWith('/images/')) return undefined
  return src.replace(/\.(jpe?g|png)$/i, '-mobile.webp')
}

export function ImageWithFallback(props: React.ImgHTMLAttributes<HTMLImageElement>) {
  const [didError, setDidError] = useState(false)

  const handleError = () => {
    setDidError(true)
  }

  const { src, alt, style, className, ...rest } = props

  if (didError) {
    return (
      <div
        className={`inline-block bg-gray-100 text-center align-middle ${className ?? ''}`}
        style={style}
      >
        <div className="flex items-center justify-center w-full h-full">
          <img src={ERROR_IMG_SRC} alt="Error loading image" {...rest} data-original-url={src} />
        </div>
      </div>
    )
  }

  const webp = webpSource(src)
  const mobileWebp = mobileWebpSource(src)

  const img = (
    <img
      src={src}
      alt={alt}
      className={className}
      style={style}
      {...rest}
      onError={handleError}
    />
  )

  if (!webp) return img

  // display:contents is known to cause severe layout bugs with replaced elements in WebKit/Safari
  // causing images to be displaced or cropped. Using w-full h-full block is much safer.
  return (
    <picture className="w-full h-full block">
      {mobileWebp && <source media="(max-width: 768px)" srcSet={mobileWebp} type="image/webp" />}
      <source srcSet={webp} type="image/webp" />
      {img}
    </picture>
  )
}
